version: '3'
services:
  elasticsearch:
    image: 'elasticsearch:8.6.0'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xmx300m
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'sail-elasticsearch:/usr/share/elasticsearch/data'
    networks:
      - sail
  kibana:
    image: 'kibana:8.6.0'
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - sail
    depends_on:
      - elasticsearch
volumes:
  # Other volumes here ...
  sail-elasticsearch:
    driver: local

networks:
  sail:
    driver: bridge